### ISSUE TITLE
Tentary v.s. generic gendered text

### ISSUE THREAD

**Issue by mount2010** [ArchboxDev/jslife#3]
Right now we're using tentary for gendered text:
${this.gender?"he":"she"} which feels clunky.
Using ES6 gets we can define gendered text which is also usable outside of Human():
```js
    get he () {
        if (this.male) return "he"; else return "she";
    }
    
    get his () {
        if (this.male) return "his"; else return "her";
    }

    get He () {
        if (this.male) return "He"; else return "She";
    }

    get His () {
        if (this.male) return "His"; else return "Her";
    }
```
which allows us to write ${this.he} / ${this.He} for text.

**Comment by ghost** [comment]
Added a logical way to implement this using templating:
[c30f94e](https://github.com/bubbie/life-simulator/commit/c30f94e1740a5cb4db87c1532844d0dc18d96776)
