### ISSUE TITLE
the higher health you have, the unhealthier you are

### ISSUE THREAD

**Issue by ghost** [ArchboxDev/jslife#4]
fix this

**Comment by snightshade** [comment]
lul

**Comment by snightshade** [comment]
what the hell, that's bad programming

**Comment by lordjbs** [comment]
hmm, to much chocolate right?

**Comment by ghost** [comment]
Fixed with the new ["""minor fixes"""](https://github.com/ArchboxDev/jslife/commit/1726e6a2512c8c30b80945d26d2782c379e44180)
